# Generated by Django 5.0.1 on 2024-05-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_user_displaypic_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='displayPic',
        ),
    ]
